---
name: Spec

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12]
        ruby: ['3.0', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false
    - name: Install Dependencies
      run: |
        bundle install
    - name: Run Tests
      run: |
        bundle exec rspec
      env:
        COVERAGE: true
